"""baseline

Revision ID: 4ddf3ebad3e8
Revises: 
Create Date: 2026-03-07 11:36:15.677305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ddf3ebad3e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('allowance_types', 'code',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='代碼',
               existing_nullable=False)
    op.alter_column('allowance_types', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='名稱',
               existing_nullable=False)
    op.alter_column('allowance_types', 'description',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='說明',
               existing_nullable=True)
    op.alter_column('allowance_types', 'is_taxable',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否課稅',
               existing_nullable=True)
    op.alter_column('allowance_types', 'sort_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='排序',
               existing_nullable=True)
    op.alter_column('allowance_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否啟用',
               existing_nullable=True)
    op.alter_column('attendance_policies', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='版本號（每次更新遞增）',
               existing_nullable=False)
    op.alter_column('attendance_policies', 'changed_by',
               existing_type=sa.VARCHAR(length=50),
               comment='最後修改人',
               existing_nullable=True)
    op.alter_column('attendance_policies', 'default_work_start',
               existing_type=sa.VARCHAR(length=5),
               comment=None,
               existing_comment='預設上班時間',
               existing_nullable=True)
    op.alter_column('attendance_policies', 'default_work_end',
               existing_type=sa.VARCHAR(length=5),
               comment=None,
               existing_comment='預設下班時間',
               existing_nullable=True)
    op.alter_column('attendance_policies', 'grace_minutes',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='遲到寬限時間(分)',
               existing_nullable=True)
    op.alter_column('attendance_policies', 'late_threshold',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='遲到幾次開始扣款',
               existing_nullable=True)
    op.alter_column('attendance_policies', 'late_deduction',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='遲到每次扣款金額',
               existing_nullable=True)
    op.alter_column('attendance_policies', 'early_leave_deduction',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='早退每次扣款金額',
               existing_nullable=True)
    op.alter_column('attendance_policies', 'missing_punch_deduction',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='未打卡每次扣款金額',
               existing_nullable=True)
    op.alter_column('attendance_policies', 'festival_bonus_months',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='入職滿幾個月可領節慶獎金',
               existing_nullable=True)
    op.alter_column('attendance_policies', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否為目前使用的政策',
               existing_nullable=True)
    op.alter_column('attendance_policies', 'effective_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='生效日期',
               existing_nullable=True)
    op.create_index('ix_attendance_emp_date', 'attendances', ['employee_id', 'attendance_date'], unique=False)
    op.alter_column('bonus_configs', 'config_year',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='年度',
               existing_nullable=False)
    op.alter_column('bonus_configs', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='版本號（每次更新遞增）',
               existing_nullable=False)
    op.alter_column('bonus_configs', 'changed_by',
               existing_type=sa.VARCHAR(length=50),
               comment='最後修改人',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'head_teacher_ab',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='班導A/B級獎金基數',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'head_teacher_c',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='班導C級獎金基數',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'assistant_teacher_ab',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='副班導A/B級獎金基數',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'assistant_teacher_c',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='副班導C級獎金基數',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'principal_festival',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='園長節慶獎金',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'director_festival',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='主任節慶獎金',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'leader_festival',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='組長節慶獎金',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'driver_festival',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='司機節慶獎金基數',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'designer_festival',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='美編節慶獎金基數',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'admin_festival',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='行政節慶獎金基數',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'principal_dividend',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='園長紅利',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'director_dividend',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='主任紅利',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'leader_dividend',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='組長紅利',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'vice_leader_dividend',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='副組長紅利',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'overtime_head_normal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='班導超額每人(大中小班)',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'overtime_head_baby',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='班導超額每人(幼幼班)',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'overtime_assistant_normal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='副班導超額每人(大中小班)',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'overtime_assistant_baby',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='副班導超額每人(幼幼班)',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'school_wide_target',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='全校目標人數',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否為目前使用的設定',
               existing_nullable=True)
    op.alter_column('bonus_settings', 'setting_year',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='年',
               existing_nullable=False)
    op.alter_column('bonus_settings', 'setting_month',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='月',
               existing_nullable=False)
    op.alter_column('bonus_settings', 'target_enrollment',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='目標人數',
               existing_nullable=True)
    op.alter_column('bonus_settings', 'current_enrollment',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='在籍人數',
               existing_nullable=True)
    op.alter_column('bonus_settings', 'festival_bonus_base',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='節慶獎金基數',
               existing_nullable=True)
    op.alter_column('bonus_settings', 'overtime_threshold',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='超額獎金門檻人數',
               existing_nullable=True)
    op.alter_column('bonus_settings', 'overtime_bonus_per_student',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='每超額一人獎金',
               existing_nullable=True)
    op.alter_column('bonus_settings', 'festival_bonus_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='節慶獎金比率',
               existing_nullable=True)
    op.alter_column('bonus_settings', 'calculated_festival_bonus',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='計算後節慶獎金',
               existing_nullable=True)
    op.alter_column('bonus_settings', 'calculated_overtime_bonus',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='計算後超額獎金',
               existing_nullable=True)
    op.alter_column('bonus_types', 'code',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='代碼',
               existing_nullable=False)
    op.alter_column('bonus_types', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='名稱',
               existing_nullable=False)
    op.alter_column('bonus_types', 'description',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='說明',
               existing_nullable=True)
    op.alter_column('bonus_types', 'is_separate_transfer',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否獨立轉帳',
               existing_nullable=True)
    op.alter_column('bonus_types', 'sort_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='排序',
               existing_nullable=True)
    op.alter_column('bonus_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否啟用',
               existing_nullable=True)
    op.alter_column('class_bonus_settings', 'year',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='年',
               existing_nullable=False)
    op.alter_column('class_bonus_settings', 'month',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='月',
               existing_nullable=False)
    op.alter_column('class_bonus_settings', 'classroom_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='班級ID',
               existing_nullable=False)
    op.alter_column('class_bonus_settings', 'target_enrollment',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='目標人數',
               existing_nullable=True)
    op.alter_column('class_bonus_settings', 'current_enrollment',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='在籍人數',
               existing_nullable=True)
    op.alter_column('class_grades', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='年級名稱',
               existing_nullable=False)
    op.alter_column('class_grades', 'age_range',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='年齡範圍',
               existing_nullable=True)
    op.alter_column('class_grades', 'sort_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='排序',
               existing_nullable=True)
    op.alter_column('class_grades', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否啟用',
               existing_nullable=True)
    op.alter_column('classrooms', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='班級名稱',
               existing_nullable=False)
    op.alter_column('classrooms', 'grade_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='年級',
               existing_nullable=True)
    op.alter_column('classrooms', 'capacity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='班級容量',
               existing_nullable=True)
    op.alter_column('classrooms', 'current_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='目前人數',
               existing_nullable=True)
    op.alter_column('classrooms', 'head_teacher_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='班導師',
               existing_nullable=True)
    op.alter_column('classrooms', 'assistant_teacher_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='副班導',
               existing_nullable=True)
    op.alter_column('classrooms', 'art_teacher_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='美師',
               existing_nullable=True)
    op.alter_column('classrooms', 'class_code',
               existing_type=sa.VARCHAR(length=20),
               comment='班級代號',
               existing_comment='班級代號 (如 114-11)',
               existing_nullable=True)
    op.alter_column('classrooms', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否啟用',
               existing_nullable=True)
    op.create_index(op.f('ix_classrooms_art_teacher_id'), 'classrooms', ['art_teacher_id'], unique=False)
    op.create_index(op.f('ix_classrooms_assistant_teacher_id'), 'classrooms', ['assistant_teacher_id'], unique=False)
    op.create_index(op.f('ix_classrooms_head_teacher_id'), 'classrooms', ['head_teacher_id'], unique=False)
    op.alter_column('daily_shifts', 'shift_type_id',
               existing_type=sa.INTEGER(),
               comment='班別（NULL 表示該日明確排休，不繼承週排班）',
               existing_nullable=True)
    op.alter_column('deduction_rules', 'rule_name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='規則名稱',
               existing_nullable=False)
    op.alter_column('deduction_rules', 'rule_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='規則類型: late/early/missing/leave',
               existing_nullable=False)
    op.alter_column('deduction_rules', 'threshold_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='達到幾次開始扣款',
               existing_nullable=True)
    op.alter_column('deduction_rules', 'deduction_per_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='每次扣款金額',
               existing_nullable=True)
    op.alter_column('deduction_rules', 'deduction_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='扣款比例',
               existing_nullable=True)
    op.alter_column('deduction_rules', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='規則說明',
               existing_nullable=True)
    op.alter_column('deduction_types', 'code',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='代碼',
               existing_nullable=False)
    op.alter_column('deduction_types', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='名稱',
               existing_nullable=False)
    op.alter_column('deduction_types', 'description',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='說明',
               existing_nullable=True)
    op.alter_column('deduction_types', 'category',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='分類: insurance/attendance/leave/other',
               existing_nullable=True)
    op.alter_column('deduction_types', 'is_employer_paid',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否雇主負擔',
               existing_nullable=True)
    op.alter_column('deduction_types', 'sort_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='排序',
               existing_nullable=True)
    op.alter_column('deduction_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否啟用',
               existing_nullable=True)
    op.alter_column('employee_allowances', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='金額',
               existing_nullable=True)
    op.alter_column('employee_allowances', 'effective_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='生效日期',
               existing_nullable=True)
    op.alter_column('employee_allowances', 'end_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='結束日期',
               existing_nullable=True)
    op.alter_column('employee_allowances', 'remark',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='備註',
               existing_nullable=True)
    op.alter_column('employee_allowances', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否啟用',
               existing_nullable=True)
    op.create_index(op.f('ix_employee_allowances_employee_id'), 'employee_allowances', ['employee_id'], unique=False)
    op.add_column('employees', sa.Column('resign_reason', sa.String(length=200), nullable=True, comment='離職原因'))
    op.add_column('employees', sa.Column('probation_end_date', sa.Date(), nullable=True, comment='試用期結束日'))
    op.alter_column('employees', 'title',
               existing_type=sa.VARCHAR(length=50),
               comment='職稱 (Legacy)',
               existing_comment='職稱',
               existing_nullable=True)
    op.alter_column('employees', 'job_title_id',
               existing_type=sa.INTEGER(),
               comment='職稱 ID',
               existing_nullable=True)
    op.alter_column('employees', 'position',
               existing_type=sa.VARCHAR(length=50),
               comment='職務 (Duty)',
               existing_comment='職稱分類 (園長/幼兒園教師/教保員等)',
               existing_nullable=True)
    op.alter_column('employees', 'classroom_id',
               existing_type=sa.INTEGER(),
               comment='所屬班級',
               existing_nullable=True)
    op.alter_column('employees', 'pension_self_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               comment='勞退自提比例 (0~0.06)',
               existing_nullable=True)
    op.alter_column('employees', 'resign_date',
               existing_type=sa.DATE(),
               comment='離職日期',
               existing_nullable=True)
    op.alter_column('employees', 'is_office_staff',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='是否為辦公室人員',
               existing_nullable=True)
    op.alter_column('employees', 'dependents',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='眷屬人數（健保計算用）',
               existing_nullable=True)
    op.alter_column('employees', 'birthday',
               existing_type=sa.DATE(),
               comment='生日',
               existing_nullable=True)
    op.alter_column('employees', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='聯絡電話',
               existing_nullable=True)
    op.alter_column('employees', 'address',
               existing_type=sa.VARCHAR(length=200),
               comment='通訊地址',
               existing_nullable=True)
    op.alter_column('employees', 'emergency_contact_name',
               existing_type=sa.VARCHAR(length=50),
               comment='緊急聯絡人',
               existing_nullable=True)
    op.alter_column('employees', 'emergency_contact_phone',
               existing_type=sa.VARCHAR(length=20),
               comment='緊急聯絡人電話',
               existing_nullable=True)
    op.alter_column('grade_targets', 'config_year',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='年度',
               existing_nullable=False)
    op.alter_column('grade_targets', 'grade_name',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='年級名稱',
               existing_nullable=False)
    op.alter_column('grade_targets', 'bonus_config_id',
               existing_type=sa.INTEGER(),
               comment='所屬獎金設定版本（NULL=舊資料）',
               existing_nullable=True)
    op.alter_column('grade_targets', 'festival_two_teachers',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='節慶-2老師目標',
               existing_nullable=True)
    op.alter_column('grade_targets', 'festival_one_teacher',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='節慶-1老師目標',
               existing_nullable=True)
    op.alter_column('grade_targets', 'festival_shared',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='節慶-共用副班導目標',
               existing_nullable=True)
    op.alter_column('grade_targets', 'overtime_two_teachers',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='超額-2老師目標',
               existing_nullable=True)
    op.alter_column('grade_targets', 'overtime_one_teacher',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='超額-1老師目標',
               existing_nullable=True)
    op.alter_column('grade_targets', 'overtime_shared',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='超額-共用副班導目標',
               existing_nullable=True)
    op.alter_column('insurance_rates', 'rate_year',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='年度',
               existing_nullable=False)
    op.alter_column('insurance_rates', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='版本號（每次更新遞增）',
               existing_nullable=False)
    op.alter_column('insurance_rates', 'changed_by',
               existing_type=sa.VARCHAR(length=50),
               comment='最後修改人',
               existing_nullable=True)
    op.alter_column('insurance_rates', 'labor_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='勞保費率 12%',
               existing_nullable=True)
    op.alter_column('insurance_rates', 'labor_employee_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='勞保員工負擔比例 20%',
               existing_nullable=True)
    op.alter_column('insurance_rates', 'labor_employer_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='勞保雇主負擔比例 70%',
               existing_nullable=True)
    op.alter_column('insurance_rates', 'labor_government_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='勞保政府負擔比例 10%',
               existing_nullable=True)
    op.alter_column('insurance_rates', 'health_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='健保費率 5.17%',
               existing_nullable=True)
    op.alter_column('insurance_rates', 'health_employee_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='健保員工負擔比例 30%',
               existing_nullable=True)
    op.alter_column('insurance_rates', 'health_employer_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='健保員工負擔比例 60%',
               existing_nullable=True)
    op.alter_column('insurance_rates', 'pension_employer_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='退休金雇主提撥比例 6%',
               existing_nullable=True)
    op.alter_column('insurance_rates', 'average_dependents',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='平均眷數',
               existing_nullable=True)
    op.alter_column('insurance_rates', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否為目前使用的費率',
               existing_nullable=True)
    op.alter_column('insurance_tables', 'labor_rate_employee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='勞保費率-員工',
               existing_nullable=True)
    op.alter_column('insurance_tables', 'labor_rate_employer',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='勞保費率-雇主',
               existing_nullable=True)
    op.alter_column('insurance_tables', 'health_rate_employee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='健保費率-員工',
               existing_nullable=True)
    op.alter_column('insurance_tables', 'health_rate_employer',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='健保費率-雇主',
               existing_nullable=True)
    op.alter_column('insurance_tables', 'pension_rate_employer',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='勞退費率-雇主提撥',
               existing_nullable=True)
    op.alter_column('insurance_tables', 'labor_employee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='勞保費-員工自付',
               existing_nullable=True)
    op.alter_column('insurance_tables', 'labor_employer',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='勞保費-雇主負擔',
               existing_nullable=True)
    op.alter_column('insurance_tables', 'health_employee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='健保費-員工自付',
               existing_nullable=True)
    op.alter_column('insurance_tables', 'health_employer',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='健保費-雇主負擔',
               existing_nullable=True)
    op.alter_column('insurance_tables', 'pension_employer_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='勞退-雇主提撥金額',
               existing_nullable=True)
    op.alter_column('leave_records', 'start_time',
               existing_type=sa.VARCHAR(length=5),
               comment='開始時間 HH:MM',
               existing_nullable=True)
    op.alter_column('leave_records', 'end_time',
               existing_type=sa.VARCHAR(length=5),
               comment='結束時間 HH:MM',
               existing_nullable=True)
    op.alter_column('leave_records', 'attachment_paths',
               existing_type=sa.TEXT(),
               comment='附件路徑清單（JSON 陣列）',
               existing_nullable=True)
    op.alter_column('leave_records', 'is_approved',
               existing_type=sa.BOOLEAN(),
               comment='是否核准 (None=待審核, True=核准, False=駁回)',
               existing_comment='是否核准',
               existing_nullable=True)
    op.alter_column('leave_records', 'rejection_reason',
               existing_type=sa.TEXT(),
               comment='駁回原因',
               existing_nullable=True)
    op.create_index('ix_leave_emp_dates', 'leave_records', ['employee_id', 'start_date', 'end_date'], unique=False)
    op.create_index('ix_meeting_emp_date', 'meeting_records', ['employee_id', 'meeting_date'], unique=False)
    op.alter_column('overtime_records', 'is_approved',
               existing_type=sa.BOOLEAN(),
               comment='是否核准 (None=待審核, True=核准, False=駁回)',
               existing_comment='是否核准',
               existing_nullable=True)
    op.create_index('ix_overtime_emp_date', 'overtime_records', ['employee_id', 'overtime_date'], unique=False)
    op.alter_column('salary_items', 'item_category',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='分類: allowance/deduction/bonus',
               existing_nullable=False)
    op.alter_column('salary_items', 'item_type_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='類型ID',
               existing_nullable=False)
    op.alter_column('salary_items', 'item_code',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='類型代碼',
               existing_nullable=False)
    op.alter_column('salary_items', 'item_name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='項目名稱',
               existing_nullable=False)
    op.alter_column('salary_items', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='金額',
               existing_nullable=True)
    op.alter_column('salary_items', 'quantity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='數量',
               existing_nullable=True)
    op.alter_column('salary_items', 'unit_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='單位金額',
               existing_nullable=True)
    op.alter_column('salary_items', 'is_employer_paid',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否雇主負擔',
               existing_nullable=True)
    op.alter_column('salary_items', 'remark',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='備註',
               existing_nullable=True)
    op.alter_column('salary_records', 'bonus_config_id',
               existing_type=sa.INTEGER(),
               comment='計算時使用的獎金設定版本',
               existing_nullable=True)
    op.alter_column('salary_records', 'attendance_policy_id',
               existing_type=sa.INTEGER(),
               comment='計算時使用的考勤政策版本',
               existing_nullable=True)
    op.alter_column('salary_records', 'overtime_pay',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               comment='加班費',
               existing_nullable=True)
    op.alter_column('salary_records', 'meeting_overtime_pay',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               comment='園務會議加班費',
               existing_nullable=True)
    op.alter_column('salary_records', 'meeting_absence_deduction',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               comment='園務會議缺席扣節慶獎金',
               existing_nullable=True)
    op.alter_column('salary_records', 'birthday_bonus',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               comment='生日禮金',
               existing_nullable=True)
    op.alter_column('salary_records', 'absence_deduction',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               comment='曠職扣款',
               existing_nullable=True)
    op.alter_column('salary_records', 'absent_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='曠職天數',
               existing_nullable=True)
    op.alter_column('salary_records', 'bonus_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='獨立轉帳獎金金額（festival+overtime+supervisor_dividend）',
               existing_comment='獨立轉帳獎金金額',
               existing_nullable=True)
    op.alter_column('salary_records', 'supervisor_dividend',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               comment='主管紅利（獨立轉帳）',
               existing_nullable=True)
    op.create_index('ix_salary_emp_ym', 'salary_records', ['employee_id', 'salary_year', 'salary_month'], unique=False)
    op.alter_column('students', 'gender',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='性別',
               existing_nullable=True)
    op.alter_column('students', 'birthday',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='生日',
               existing_nullable=True)
    op.alter_column('students', 'classroom_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='班級',
               existing_nullable=True)
    op.alter_column('students', 'enrollment_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='入學日期',
               existing_nullable=True)
    op.alter_column('students', 'graduation_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='畢業日期',
               existing_nullable=True)
    op.alter_column('students', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='狀態',
               existing_nullable=True)
    op.alter_column('students', 'parent_name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='家長姓名',
               existing_nullable=True)
    op.alter_column('students', 'parent_phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='聯絡電話',
               existing_nullable=True)
    op.alter_column('students', 'address',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='地址',
               existing_nullable=True)
    op.alter_column('students', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='備註',
               existing_nullable=True)
    op.alter_column('students', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否在讀',
               existing_nullable=True)
    op.alter_column('students', 'status_tag',
               existing_type=sa.VARCHAR(length=50),
               comment='狀態標籤',
               existing_comment='狀態標籤 (新生/不足齡/特殊生等)',
               existing_nullable=True)
    op.create_index('ix_student_classroom', 'students', ['classroom_id', 'is_active'], unique=False)
    op.alter_column('system_configs', 'config_key',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='設定鍵名',
               existing_nullable=False)
    op.alter_column('system_configs', 'config_value',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='設定值 (JSON)',
               existing_nullable=False)
    op.alter_column('system_configs', 'config_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='設定類別',
               existing_nullable=True)
    op.alter_column('system_configs', 'description',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='設定說明',
               existing_nullable=True)
    op.alter_column('users', 'permissions',
               existing_type=sa.BIGINT(),
               server_default=None,
               comment='功能模組權限位元遮罩 (-1=全部權限, NULL=使用角色預設)',
               existing_nullable=True)
    op.alter_column('users', 'must_change_password',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True,
               comment='是否強制下次登入修改密碼')
    op.alter_column('users', 'token_version',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='Token 版本號；帳號停用或權限變更時遞增，使所有現有 Token 無法刷新',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'token_version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='Token 版本號；帳號停用或權限變更時遞增，使所有現有 Token 無法刷新',
               existing_nullable=False)
    op.alter_column('users', 'must_change_password',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False,
               comment=None,
               existing_comment='是否強制下次登入修改密碼')
    op.alter_column('users', 'permissions',
               existing_type=sa.BIGINT(),
               server_default=sa.text("'-1'::integer"),
               comment=None,
               existing_comment='功能模組權限位元遮罩 (-1=全部權限, NULL=使用角色預設)',
               existing_nullable=True)
    op.alter_column('system_configs', 'description',
               existing_type=sa.VARCHAR(length=200),
               comment='設定說明',
               existing_nullable=True)
    op.alter_column('system_configs', 'config_type',
               existing_type=sa.VARCHAR(length=50),
               comment='設定類別',
               existing_nullable=True)
    op.alter_column('system_configs', 'config_value',
               existing_type=sa.TEXT(),
               comment='設定值 (JSON)',
               existing_nullable=False)
    op.alter_column('system_configs', 'config_key',
               existing_type=sa.VARCHAR(length=100),
               comment='設定鍵名',
               existing_nullable=False)
    op.drop_index('ix_student_classroom', table_name='students')
    op.alter_column('students', 'status_tag',
               existing_type=sa.VARCHAR(length=50),
               comment='狀態標籤 (新生/不足齡/特殊生等)',
               existing_comment='狀態標籤',
               existing_nullable=True)
    op.alter_column('students', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否在讀',
               existing_nullable=True)
    op.alter_column('students', 'notes',
               existing_type=sa.TEXT(),
               comment='備註',
               existing_nullable=True)
    op.alter_column('students', 'address',
               existing_type=sa.VARCHAR(length=200),
               comment='地址',
               existing_nullable=True)
    op.alter_column('students', 'parent_phone',
               existing_type=sa.VARCHAR(length=20),
               comment='聯絡電話',
               existing_nullable=True)
    op.alter_column('students', 'parent_name',
               existing_type=sa.VARCHAR(length=50),
               comment='家長姓名',
               existing_nullable=True)
    op.alter_column('students', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='狀態',
               existing_nullable=True)
    op.alter_column('students', 'graduation_date',
               existing_type=sa.DATE(),
               comment='畢業日期',
               existing_nullable=True)
    op.alter_column('students', 'enrollment_date',
               existing_type=sa.DATE(),
               comment='入學日期',
               existing_nullable=True)
    op.alter_column('students', 'classroom_id',
               existing_type=sa.INTEGER(),
               comment='班級',
               existing_nullable=True)
    op.alter_column('students', 'birthday',
               existing_type=sa.DATE(),
               comment='生日',
               existing_nullable=True)
    op.alter_column('students', 'gender',
               existing_type=sa.VARCHAR(length=10),
               comment='性別',
               existing_nullable=True)
    op.drop_index('ix_salary_emp_ym', table_name='salary_records')
    op.alter_column('salary_records', 'supervisor_dividend',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='主管紅利（獨立轉帳）',
               existing_nullable=True)
    op.alter_column('salary_records', 'bonus_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='獨立轉帳獎金金額',
               existing_comment='獨立轉帳獎金金額（festival+overtime+supervisor_dividend）',
               existing_nullable=True)
    op.alter_column('salary_records', 'absent_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='曠職天數',
               existing_nullable=True)
    op.alter_column('salary_records', 'absence_deduction',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='曠職扣款',
               existing_nullable=True)
    op.alter_column('salary_records', 'birthday_bonus',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='生日禮金',
               existing_nullable=True)
    op.alter_column('salary_records', 'meeting_absence_deduction',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='園務會議缺席扣節慶獎金',
               existing_nullable=True)
    op.alter_column('salary_records', 'meeting_overtime_pay',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='園務會議加班費',
               existing_nullable=True)
    op.alter_column('salary_records', 'overtime_pay',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='加班費',
               existing_nullable=True)
    op.alter_column('salary_records', 'attendance_policy_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='計算時使用的考勤政策版本',
               existing_nullable=True)
    op.alter_column('salary_records', 'bonus_config_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='計算時使用的獎金設定版本',
               existing_nullable=True)
    op.alter_column('salary_items', 'remark',
               existing_type=sa.TEXT(),
               comment='備註',
               existing_nullable=True)
    op.alter_column('salary_items', 'is_employer_paid',
               existing_type=sa.BOOLEAN(),
               comment='是否雇主負擔',
               existing_nullable=True)
    op.alter_column('salary_items', 'unit_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='單位金額',
               existing_nullable=True)
    op.alter_column('salary_items', 'quantity',
               existing_type=sa.INTEGER(),
               comment='數量',
               existing_nullable=True)
    op.alter_column('salary_items', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='金額',
               existing_nullable=True)
    op.alter_column('salary_items', 'item_name',
               existing_type=sa.VARCHAR(length=50),
               comment='項目名稱',
               existing_nullable=False)
    op.alter_column('salary_items', 'item_code',
               existing_type=sa.VARCHAR(length=30),
               comment='類型代碼',
               existing_nullable=False)
    op.alter_column('salary_items', 'item_type_id',
               existing_type=sa.INTEGER(),
               comment='類型ID',
               existing_nullable=False)
    op.alter_column('salary_items', 'item_category',
               existing_type=sa.VARCHAR(length=20),
               comment='分類: allowance/deduction/bonus',
               existing_nullable=False)
    op.drop_index('ix_overtime_emp_date', table_name='overtime_records')
    op.alter_column('overtime_records', 'is_approved',
               existing_type=sa.BOOLEAN(),
               comment='是否核准',
               existing_comment='是否核准 (None=待審核, True=核准, False=駁回)',
               existing_nullable=True)
    op.drop_index('ix_meeting_emp_date', table_name='meeting_records')
    op.drop_index('ix_leave_emp_dates', table_name='leave_records')
    op.alter_column('leave_records', 'rejection_reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='駁回原因',
               existing_nullable=True)
    op.alter_column('leave_records', 'is_approved',
               existing_type=sa.BOOLEAN(),
               comment='是否核准',
               existing_comment='是否核准 (None=待審核, True=核准, False=駁回)',
               existing_nullable=True)
    op.alter_column('leave_records', 'attachment_paths',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='附件路徑清單（JSON 陣列）',
               existing_nullable=True)
    op.alter_column('leave_records', 'end_time',
               existing_type=sa.VARCHAR(length=5),
               comment=None,
               existing_comment='結束時間 HH:MM',
               existing_nullable=True)
    op.alter_column('leave_records', 'start_time',
               existing_type=sa.VARCHAR(length=5),
               comment=None,
               existing_comment='開始時間 HH:MM',
               existing_nullable=True)
    op.alter_column('insurance_tables', 'pension_employer_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='勞退-雇主提撥金額',
               existing_nullable=True)
    op.alter_column('insurance_tables', 'health_employer',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='健保費-雇主負擔',
               existing_nullable=True)
    op.alter_column('insurance_tables', 'health_employee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='健保費-員工自付',
               existing_nullable=True)
    op.alter_column('insurance_tables', 'labor_employer',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='勞保費-雇主負擔',
               existing_nullable=True)
    op.alter_column('insurance_tables', 'labor_employee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='勞保費-員工自付',
               existing_nullable=True)
    op.alter_column('insurance_tables', 'pension_rate_employer',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='勞退費率-雇主提撥',
               existing_nullable=True)
    op.alter_column('insurance_tables', 'health_rate_employer',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='健保費率-雇主',
               existing_nullable=True)
    op.alter_column('insurance_tables', 'health_rate_employee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='健保費率-員工',
               existing_nullable=True)
    op.alter_column('insurance_tables', 'labor_rate_employer',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='勞保費率-雇主',
               existing_nullable=True)
    op.alter_column('insurance_tables', 'labor_rate_employee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='勞保費率-員工',
               existing_nullable=True)
    op.alter_column('insurance_rates', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否為目前使用的費率',
               existing_nullable=True)
    op.alter_column('insurance_rates', 'average_dependents',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='平均眷數',
               existing_nullable=True)
    op.alter_column('insurance_rates', 'pension_employer_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='退休金雇主提撥比例 6%',
               existing_nullable=True)
    op.alter_column('insurance_rates', 'health_employer_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='健保員工負擔比例 60%',
               existing_nullable=True)
    op.alter_column('insurance_rates', 'health_employee_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='健保員工負擔比例 30%',
               existing_nullable=True)
    op.alter_column('insurance_rates', 'health_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='健保費率 5.17%',
               existing_nullable=True)
    op.alter_column('insurance_rates', 'labor_government_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='勞保政府負擔比例 10%',
               existing_nullable=True)
    op.alter_column('insurance_rates', 'labor_employer_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='勞保雇主負擔比例 70%',
               existing_nullable=True)
    op.alter_column('insurance_rates', 'labor_employee_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='勞保員工負擔比例 20%',
               existing_nullable=True)
    op.alter_column('insurance_rates', 'labor_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='勞保費率 12%',
               existing_nullable=True)
    op.alter_column('insurance_rates', 'changed_by',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='最後修改人',
               existing_nullable=True)
    op.alter_column('insurance_rates', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               comment=None,
               existing_comment='版本號（每次更新遞增）',
               existing_nullable=False)
    op.alter_column('insurance_rates', 'rate_year',
               existing_type=sa.INTEGER(),
               comment='年度',
               existing_nullable=False)
    op.alter_column('grade_targets', 'overtime_shared',
               existing_type=sa.INTEGER(),
               comment='超額-共用副班導目標',
               existing_nullable=True)
    op.alter_column('grade_targets', 'overtime_one_teacher',
               existing_type=sa.INTEGER(),
               comment='超額-1老師目標',
               existing_nullable=True)
    op.alter_column('grade_targets', 'overtime_two_teachers',
               existing_type=sa.INTEGER(),
               comment='超額-2老師目標',
               existing_nullable=True)
    op.alter_column('grade_targets', 'festival_shared',
               existing_type=sa.INTEGER(),
               comment='節慶-共用副班導目標',
               existing_nullable=True)
    op.alter_column('grade_targets', 'festival_one_teacher',
               existing_type=sa.INTEGER(),
               comment='節慶-1老師目標',
               existing_nullable=True)
    op.alter_column('grade_targets', 'festival_two_teachers',
               existing_type=sa.INTEGER(),
               comment='節慶-2老師目標',
               existing_nullable=True)
    op.alter_column('grade_targets', 'bonus_config_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所屬獎金設定版本（NULL=舊資料）',
               existing_nullable=True)
    op.alter_column('grade_targets', 'grade_name',
               existing_type=sa.VARCHAR(length=20),
               comment='年級名稱',
               existing_nullable=False)
    op.alter_column('grade_targets', 'config_year',
               existing_type=sa.INTEGER(),
               comment='年度',
               existing_nullable=False)
    op.alter_column('employees', 'emergency_contact_phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='緊急聯絡人電話',
               existing_nullable=True)
    op.alter_column('employees', 'emergency_contact_name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='緊急聯絡人',
               existing_nullable=True)
    op.alter_column('employees', 'address',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='通訊地址',
               existing_nullable=True)
    op.alter_column('employees', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='聯絡電話',
               existing_nullable=True)
    op.alter_column('employees', 'birthday',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='生日',
               existing_nullable=True)
    op.alter_column('employees', 'dependents',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='眷屬人數（健保計算用）',
               existing_nullable=True)
    op.alter_column('employees', 'is_office_staff',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='是否為辦公室人員',
               existing_nullable=True)
    op.alter_column('employees', 'resign_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='離職日期',
               existing_nullable=True)
    op.alter_column('employees', 'pension_self_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='勞退自提比例 (0~0.06)',
               existing_nullable=True)
    op.alter_column('employees', 'classroom_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所屬班級',
               existing_nullable=True)
    op.alter_column('employees', 'position',
               existing_type=sa.VARCHAR(length=50),
               comment='職稱分類 (園長/幼兒園教師/教保員等)',
               existing_comment='職務 (Duty)',
               existing_nullable=True)
    op.alter_column('employees', 'job_title_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='職稱 ID',
               existing_nullable=True)
    op.alter_column('employees', 'title',
               existing_type=sa.VARCHAR(length=50),
               comment='職稱',
               existing_comment='職稱 (Legacy)',
               existing_nullable=True)
    op.drop_column('employees', 'probation_end_date')
    op.drop_column('employees', 'resign_reason')
    op.drop_index(op.f('ix_employee_allowances_employee_id'), table_name='employee_allowances')
    op.alter_column('employee_allowances', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否啟用',
               existing_nullable=True)
    op.alter_column('employee_allowances', 'remark',
               existing_type=sa.TEXT(),
               comment='備註',
               existing_nullable=True)
    op.alter_column('employee_allowances', 'end_date',
               existing_type=sa.DATE(),
               comment='結束日期',
               existing_nullable=True)
    op.alter_column('employee_allowances', 'effective_date',
               existing_type=sa.DATE(),
               comment='生效日期',
               existing_nullable=True)
    op.alter_column('employee_allowances', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='金額',
               existing_nullable=True)
    op.alter_column('deduction_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否啟用',
               existing_nullable=True)
    op.alter_column('deduction_types', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='排序',
               existing_nullable=True)
    op.alter_column('deduction_types', 'is_employer_paid',
               existing_type=sa.BOOLEAN(),
               comment='是否雇主負擔',
               existing_nullable=True)
    op.alter_column('deduction_types', 'category',
               existing_type=sa.VARCHAR(length=20),
               comment='分類: insurance/attendance/leave/other',
               existing_nullable=True)
    op.alter_column('deduction_types', 'description',
               existing_type=sa.VARCHAR(length=200),
               comment='說明',
               existing_nullable=True)
    op.alter_column('deduction_types', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='名稱',
               existing_nullable=False)
    op.alter_column('deduction_types', 'code',
               existing_type=sa.VARCHAR(length=30),
               comment='代碼',
               existing_nullable=False)
    op.alter_column('deduction_rules', 'description',
               existing_type=sa.TEXT(),
               comment='規則說明',
               existing_nullable=True)
    op.alter_column('deduction_rules', 'deduction_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='扣款比例',
               existing_nullable=True)
    op.alter_column('deduction_rules', 'deduction_per_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='每次扣款金額',
               existing_nullable=True)
    op.alter_column('deduction_rules', 'threshold_count',
               existing_type=sa.INTEGER(),
               comment='達到幾次開始扣款',
               existing_nullable=True)
    op.alter_column('deduction_rules', 'rule_type',
               existing_type=sa.VARCHAR(length=20),
               comment='規則類型: late/early/missing/leave',
               existing_nullable=False)
    op.alter_column('deduction_rules', 'rule_name',
               existing_type=sa.VARCHAR(length=50),
               comment='規則名稱',
               existing_nullable=False)
    op.alter_column('daily_shifts', 'shift_type_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='班別（NULL 表示該日明確排休，不繼承週排班）',
               existing_nullable=True)
    op.drop_index(op.f('ix_classrooms_head_teacher_id'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_assistant_teacher_id'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_art_teacher_id'), table_name='classrooms')
    op.alter_column('classrooms', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否啟用',
               existing_nullable=True)
    op.alter_column('classrooms', 'class_code',
               existing_type=sa.VARCHAR(length=20),
               comment='班級代號 (如 114-11)',
               existing_comment='班級代號',
               existing_nullable=True)
    op.alter_column('classrooms', 'art_teacher_id',
               existing_type=sa.INTEGER(),
               comment='美師',
               existing_nullable=True)
    op.alter_column('classrooms', 'assistant_teacher_id',
               existing_type=sa.INTEGER(),
               comment='副班導',
               existing_nullable=True)
    op.alter_column('classrooms', 'head_teacher_id',
               existing_type=sa.INTEGER(),
               comment='班導師',
               existing_nullable=True)
    op.alter_column('classrooms', 'current_count',
               existing_type=sa.INTEGER(),
               comment='目前人數',
               existing_nullable=True)
    op.alter_column('classrooms', 'capacity',
               existing_type=sa.INTEGER(),
               comment='班級容量',
               existing_nullable=True)
    op.alter_column('classrooms', 'grade_id',
               existing_type=sa.INTEGER(),
               comment='年級',
               existing_nullable=True)
    op.alter_column('classrooms', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='班級名稱',
               existing_nullable=False)
    op.alter_column('class_grades', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否啟用',
               existing_nullable=True)
    op.alter_column('class_grades', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='排序',
               existing_nullable=True)
    op.alter_column('class_grades', 'age_range',
               existing_type=sa.VARCHAR(length=20),
               comment='年齡範圍',
               existing_nullable=True)
    op.alter_column('class_grades', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='年級名稱',
               existing_nullable=False)
    op.alter_column('class_bonus_settings', 'current_enrollment',
               existing_type=sa.INTEGER(),
               comment='在籍人數',
               existing_nullable=True)
    op.alter_column('class_bonus_settings', 'target_enrollment',
               existing_type=sa.INTEGER(),
               comment='目標人數',
               existing_nullable=True)
    op.alter_column('class_bonus_settings', 'classroom_id',
               existing_type=sa.INTEGER(),
               comment='班級ID',
               existing_nullable=False)
    op.alter_column('class_bonus_settings', 'month',
               existing_type=sa.INTEGER(),
               comment='月',
               existing_nullable=False)
    op.alter_column('class_bonus_settings', 'year',
               existing_type=sa.INTEGER(),
               comment='年',
               existing_nullable=False)
    op.alter_column('bonus_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否啟用',
               existing_nullable=True)
    op.alter_column('bonus_types', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='排序',
               existing_nullable=True)
    op.alter_column('bonus_types', 'is_separate_transfer',
               existing_type=sa.BOOLEAN(),
               comment='是否獨立轉帳',
               existing_nullable=True)
    op.alter_column('bonus_types', 'description',
               existing_type=sa.VARCHAR(length=200),
               comment='說明',
               existing_nullable=True)
    op.alter_column('bonus_types', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='名稱',
               existing_nullable=False)
    op.alter_column('bonus_types', 'code',
               existing_type=sa.VARCHAR(length=30),
               comment='代碼',
               existing_nullable=False)
    op.alter_column('bonus_settings', 'calculated_overtime_bonus',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='計算後超額獎金',
               existing_nullable=True)
    op.alter_column('bonus_settings', 'calculated_festival_bonus',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='計算後節慶獎金',
               existing_nullable=True)
    op.alter_column('bonus_settings', 'festival_bonus_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='節慶獎金比率',
               existing_nullable=True)
    op.alter_column('bonus_settings', 'overtime_bonus_per_student',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='每超額一人獎金',
               existing_nullable=True)
    op.alter_column('bonus_settings', 'overtime_threshold',
               existing_type=sa.INTEGER(),
               comment='超額獎金門檻人數',
               existing_nullable=True)
    op.alter_column('bonus_settings', 'festival_bonus_base',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='節慶獎金基數',
               existing_nullable=True)
    op.alter_column('bonus_settings', 'current_enrollment',
               existing_type=sa.INTEGER(),
               comment='在籍人數',
               existing_nullable=True)
    op.alter_column('bonus_settings', 'target_enrollment',
               existing_type=sa.INTEGER(),
               comment='目標人數',
               existing_nullable=True)
    op.alter_column('bonus_settings', 'setting_month',
               existing_type=sa.INTEGER(),
               comment='月',
               existing_nullable=False)
    op.alter_column('bonus_settings', 'setting_year',
               existing_type=sa.INTEGER(),
               comment='年',
               existing_nullable=False)
    op.alter_column('bonus_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否為目前使用的設定',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'school_wide_target',
               existing_type=sa.INTEGER(),
               comment='全校目標人數',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'overtime_assistant_baby',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='副班導超額每人(幼幼班)',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'overtime_assistant_normal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='副班導超額每人(大中小班)',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'overtime_head_baby',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='班導超額每人(幼幼班)',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'overtime_head_normal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='班導超額每人(大中小班)',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'vice_leader_dividend',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='副組長紅利',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'leader_dividend',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='組長紅利',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'director_dividend',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='主任紅利',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'principal_dividend',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='園長紅利',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'admin_festival',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='行政節慶獎金基數',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'designer_festival',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='美編節慶獎金基數',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'driver_festival',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='司機節慶獎金基數',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'leader_festival',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='組長節慶獎金',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'director_festival',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='主任節慶獎金',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'principal_festival',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='園長節慶獎金',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'assistant_teacher_c',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='副班導C級獎金基數',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'assistant_teacher_ab',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='副班導A/B級獎金基數',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'head_teacher_c',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='班導C級獎金基數',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'head_teacher_ab',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='班導A/B級獎金基數',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'changed_by',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='最後修改人',
               existing_nullable=True)
    op.alter_column('bonus_configs', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               comment=None,
               existing_comment='版本號（每次更新遞增）',
               existing_nullable=False)
    op.alter_column('bonus_configs', 'config_year',
               existing_type=sa.INTEGER(),
               comment='年度',
               existing_nullable=False)
    op.drop_index('ix_attendance_emp_date', table_name='attendances')
    op.alter_column('attendance_policies', 'effective_date',
               existing_type=sa.DATE(),
               comment='生效日期',
               existing_nullable=True)
    op.alter_column('attendance_policies', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否為目前使用的政策',
               existing_nullable=True)
    op.alter_column('attendance_policies', 'festival_bonus_months',
               existing_type=sa.INTEGER(),
               comment='入職滿幾個月可領節慶獎金',
               existing_nullable=True)
    op.alter_column('attendance_policies', 'missing_punch_deduction',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='未打卡每次扣款金額',
               existing_nullable=True)
    op.alter_column('attendance_policies', 'early_leave_deduction',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='早退每次扣款金額',
               existing_nullable=True)
    op.alter_column('attendance_policies', 'late_deduction',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='遲到每次扣款金額',
               existing_nullable=True)
    op.alter_column('attendance_policies', 'late_threshold',
               existing_type=sa.INTEGER(),
               comment='遲到幾次開始扣款',
               existing_nullable=True)
    op.alter_column('attendance_policies', 'grace_minutes',
               existing_type=sa.INTEGER(),
               comment='遲到寬限時間(分)',
               existing_nullable=True)
    op.alter_column('attendance_policies', 'default_work_end',
               existing_type=sa.VARCHAR(length=5),
               comment='預設下班時間',
               existing_nullable=True)
    op.alter_column('attendance_policies', 'default_work_start',
               existing_type=sa.VARCHAR(length=5),
               comment='預設上班時間',
               existing_nullable=True)
    op.alter_column('attendance_policies', 'changed_by',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='最後修改人',
               existing_nullable=True)
    op.alter_column('attendance_policies', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               comment=None,
               existing_comment='版本號（每次更新遞增）',
               existing_nullable=False)
    op.alter_column('allowance_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否啟用',
               existing_nullable=True)
    op.alter_column('allowance_types', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='排序',
               existing_nullable=True)
    op.alter_column('allowance_types', 'is_taxable',
               existing_type=sa.BOOLEAN(),
               comment='是否課稅',
               existing_nullable=True)
    op.alter_column('allowance_types', 'description',
               existing_type=sa.VARCHAR(length=200),
               comment='說明',
               existing_nullable=True)
    op.alter_column('allowance_types', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='名稱',
               existing_nullable=False)
    op.alter_column('allowance_types', 'code',
               existing_type=sa.VARCHAR(length=30),
               comment='代碼',
               existing_nullable=False)
    # ### end Alembic commands ###
