"""ErrorCode registry — 集中註冊家長端 BusinessError code，避免 typo。

家長端 frontend errorCodeRegistry.ts 須與此清單對齊（手動同步；
follow-up codegen 可從 OpenAPI 抓 discriminator）。
"""

from enum import Enum


class ErrorCode(str, Enum):
    # 家長綁定流程
    BIND_CODE_INVALID = "BIND_CODE_INVALID"
    BIND_CODE_EXPIRED = "BIND_CODE_EXPIRED"
    BIND_CODE_ALREADY_USED = "BIND_CODE_ALREADY_USED"
    # 既有 auth.py BusinessError code（_diagnose_binding_failure 已 in-use）
    BIND_CODE_NOT_FOUND = "BIND_CODE_NOT_FOUND"
    BIND_CODE_USED = "BIND_CODE_USED"

    # LIFF 認證
    LINE_BINDING_EXPIRED = "LINE_BINDING_EXPIRED"
    LINE_BINDING_NOT_FOUND = "LINE_BINDING_NOT_FOUND"
    LINE_PROFILE_FETCH_FAILED = "LINE_PROFILE_FETCH_FAILED"

    # 家長存取資源
    STUDENT_NOT_FOUND = "STUDENT_NOT_FOUND"
    STUDENT_NOT_LINKED_TO_PARENT = "STUDENT_NOT_LINKED_TO_PARENT"
    PORTAL_DATA_UNAVAILABLE = "PORTAL_DATA_UNAVAILABLE"
    CONTACT_BOOK_NOT_PUBLISHED = "CONTACT_BOOK_NOT_PUBLISHED"

    # 家長端通用
    CONSENT_REQUIRED = "CONSENT_REQUIRED"
    DSR_REQUEST_INVALID = "DSR_REQUEST_INVALID"
    PARENT_NOT_AUTHORIZED = "PARENT_NOT_AUTHORIZED"
